# Generated by Django 2.2.2 on 2019-06-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_movieimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('first_name', 'last_name')},
        ),
    ]
